### ISSUE TITLE
Documentation or Sample App

### ISSUE THREAD

**Issue by cindro** [folkelib/Folke.Localization.Json#1]
I am interesting in trying out this library but can't find enough documentation so I can use it on my ASP.NET Core RC2 app.

Are you able to provide more documentation or a sample app? thank you.

**Comment by acastaner** [comment]
You can use this project as a sample app: https://github.com/folkelib/Folke.Etxea

It's got a bunch of dependencies on other projects, and is still quite a work in progress, but that should get you started. We're still building the whole architecture and try to keep up with all the .NET Core changes, once that settles we'll provide a proper documentation.
